import type { User } from "../lib/type";

export const defaultUsers: User[] = [
  {
    id: "1",
    username: "FabDau",
    email: "fabio@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    birthday: "2005-03-15",
    userFirstName: "Fabio",
    userLastName: "Müller",
    joiningDate: "2023-10-01",
    following: ["2", "3"],
    followers: ["2"],
  },
  {
    id: "2",
    username: "mattheo",
    email: "lena@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    birthday: "2004-08-22",
    userFirstName: "Lena",
    userLastName: "Schneider",
    joiningDate: "2024-01-15",
    following: ["1"],
    followers: ["1", "3"],
  },
  {
    id: "3",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "4",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "5",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "6",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "7",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "8",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "9",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "10",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "11",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "12",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "13",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "14",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "15",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "16",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "17",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "18",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Marco",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
  {
    id: "19",
    username: "theRealOtto",
    email: "marco@example.com",
    profilePictureUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    birthday: "2003-11-05",
    userFirstName: "Leandro",
    userLastName: "Weber",
    joiningDate: "2024-06-12",
    following: ["1"],
    followers: ["1", "2"],
  },
];
